url: https://sipg-isr-test.github.io
baseurl: 

# Site settings
title: "" 
email: sipg@isr.ist.utl.pt
description: "The Signal and Image Processing Group (SIPG) at ISR Lisbon conducts cutting-edge research in signal processing on manifolds, with applications in wireless communications, underwater acoustics, image and video analysis, and 3D modeling. Discover our work in optimization, filtering, manifold learning, and statistical modeling."
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.


# Team names, titles and social links
people:
- name: João Paulo Costeira
  pic: JPCosteira
  position: Principal Investigator
  social:
    - icon: fas
      title: user
      url: https://jpcosteira.github.io/

    - icon: fab
      title: google-scholar
      url: https://scholar.google.com/citations?user=Xi33QRIAAAAJ&hl=pt-PT&oi=ao 

    - icon: fab
      title: linkedin-in
      url: https://www.linkedin.com/in/joao-paulo-costeira-b4a5401/ 



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: researchgate
    url: https://www.researchgate.net/lab/Signal-and-Image-Processing-Group-Joao-Costeira 
  - title: github
    url: https://github.com/sipg-isr

# Postal address (add as many lines as necessary)
address:
  - line: Av. Rovisco Pais 1
  - line: 1049-001 Lisboa

# Build settings
markdown: kramdown
permalink: pretty