url: https://sipg-isr-test.github.io
baseurl: 

# Site settings
title: "" 
email: sipg@isr.ist.utl.pt
description: "The Signal and Image Processing Group (SIPG) at ISR Lisbon conducts cutting-edge research in signal processing on manifolds, with applications in wireless communications, underwater acoustics, image and video analysis, and 3D modeling. Discover our work in optimization, filtering, manifold learning, and statistical modeling."
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.


# Team names, titles and social links
people:
- name: João Paulo Costeira
  pic: JPCosteira
  position: Principal Investigator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/sipg-isr

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty