url: https://sipg-isr-test.github.io
baseurl: 

# Site settings
title: "" 
email: sipg@isr.ist.utl.pt
description: "The Signal and Image Processing Group (SIPG) at ISR Lisbon conducts cutting-edge research in signal processing on manifolds, with applications in wireless communications, underwater acoustics, image and video analysis, and 3D modeling. Discover our work in optimization, filtering, manifold learning, and statistical modeling."
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.


# Team names, titles and social links
people:
- name: João Paulo Costeira
  pic: JPCosteira
  position: Associate Professor (IST)
  category: Principal Investigator
  social:
    - icon: fas
      title: user
      url: https://jpcosteira.github.io/

    - icon: fab
      title: google-scholar
      url: https://scholar.google.com/citations?user=Xi33QRIAAAAJ&hl=pt-PT&oi=ao 

    - icon: fab
      title: linkedin-in
      url: https://www.linkedin.com/in/joao-paulo-costeira-b4a5401/ 

- name: Pedro Aguiar
  pic: PedroAguiar
  position: Associate Professor (IST)
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Diogo Araújo
  pic: NoPhoto
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:


- name: Francisco Maria Calisto
  pic: FransciscoCalisto
  position: Research Assistant
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: João Carvalho
  pic: JoaoCarvalho
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: José Celestino
  pic: NoPhoto
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Miguel Dias
  pic: MiguelDias
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Manuel Ferreira
  pic: ManuelFerreira
  position: Research Fellow
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: João Pedro Gomes
  pic: JoaoPedroGomes
  position: Associate Professor (IST)
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Duarte Leão
  pic: NoPhoto
  position: Research Fellow
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Filipa Lino
  pic: FilipaLino
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Manuel Marques
  pic: ManuelMArques
  position: Post-Doc Researcher
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Gonçalo Matos
  pic: NoPhoto
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:
  
- name: Gabriel Moreira
  pic: GabrielMoreira
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Hemaxi Narotamo
  pic: HemaxiNarotamo
  position: Ph.D. Student
  category: Past Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Jacinto Nascimento
  pic: JacintoNascimento
  position: Assistant Professor (IST)
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Carlos Santiago
  pic: CarlosSantiago
  position: Assistant Researcher and Invited Assistent Professor
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Margarida Silveira
  pic: MargaridaSilveira
  position: Associate Professor (IST)
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Bárbara Tavares
  pic: BarbaraTavares
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:


- name: Pedro Valdeira
  pic: PedroValdeira
  position: Ph.D. Student
  category: Past Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: David Vicente
  pic: DavidVicente
  position: Ph.D. Student
  category: Past Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: Rúben Viegas
  pic: RubenViegas
  position: Ph.D. Student
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:

- name: João Xavier
  pic: NoPhoto
  position: Associate Professor (IST)
  category: Current Member
  social:
    - icon: fas
      title: user
      url: 

    - icon: fab
      title: google-scholar
      url: 

    - icon: fab
      title: linkedin-in
      url:


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: researchgate
    url: https://www.researchgate.net/lab/Signal-and-Image-Processing-Group-Joao-Costeira 
  - title: github
    url: https://github.com/sipg-isr

# Postal address (add as many lines as necessary)
address:
  - line: Av. Rovisco Pais 1
  - line: 1049-001 Lisboa

# Build settings
markdown: kramdown
permalink: pretty